services:
  - type: web
    name: bot-roleta
    env: python
    plan: free
    buildCommand: |
      bash install_chrome.sh
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
