services:
  - type: web
    name: bot-roleta
    env: python
    buildCommand: |
      bash install_chrome.sh
      pip install -r requirements.txt
    startCommand: streamlit run bot_streamlit.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
