services:
  - type: web
    name: roleta-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
